### ISSUE TITLE
non-free license

### ISSUE THREAD

**Issue by bzed** [ralph-hm/check_paloalto#1]
hi,

unfortunately the license you've chosen does not allow to distribute modified versions of your code and ensures that it is basically impossible to keep it updated to more recent PA versions - and it will also be impossible for Linux Distributions like Debian to ship your check_paloalto. Please consider to change it to a more open license like http://creativecommons.org/licenses/by-sa/4.0/

thanks,
bernd

**Comment by r4sky0** [comment]
Hi Bernd,

we changed the licence to CC BY-SA 4.0.

Cheers
Ralph
