### ISSUE TITLE
New name for hdd devices in PA5220's

### ISSUE THREAD

**Issue by gdijk** [ralph-hm/check_paloalto#12]
Hi Ralph,

Is it possible to implement the new hard disk device names the PA5220's use?
Our 850's and 3020's use /dev/sdax
Our 5220's use /dev/mdx

kind regards 

Geert van Dijk

**Comment by gdijk** [comment]
In a test I changed the following:

Line 43
available_hdds = re.findall('(sda\d.*?)(?=/)', soup.result.string)
to
available_hdds = re.findall('(md\d.*?|sda\d.*?)(?=/)', soup.result.string)

and

Line 45
sda = re.findall('(sda\d)', hdd)[0]
to
sda = re.findall('(md\d|sda\d)', hdd)[0]

I'm a total ... when it comes to regex but for now it works ;-)

**Comment by r4sky0** [comment]
Hi Geert,

sorry for the late reply. 

Currently, I don't have access to a PA anymore. Thats why I'm unable to test changes directly to the REST API and therefore I can't change the code.

But your solution looks good and I'm glad you found a solution to this problem. It would be great, if you create a pull request to propose your changes, so I can merge them into the actual code.

Kind regards
Ralph

**Comment by gdijk** [comment]
I'll do my best ;-)

**Comment by r4sky0** [comment]
Thank you! I will merge it into master next week!
