### ISSUE TITLE
Certificate check issue

### ISSUE THREAD

**Issue by gdijk** [ralph-hm/check_paloalto#13]
Hi,

we've got some certificates without time (only month day year)
changed the certificate.py code a bit:
from 
                date_object = datetime.strptime(not_valid_after, '%b %d %H:%M:%S %Y')
to
            try:
                date_object = datetime.strptime(not_valid_after, '%b %d %H:%M:%S %Y')
            except ValueError:
                date_object = datetime.strptime(not_valid_after, '%b %d %Y')

**Comment by r4sky0** [comment]
Thanks for the catch. Can you create a pull request to add this?

Kind regards
Ralph

**Comment by gdijk** [comment]
I'll do my best for both of them Ralph

**Comment by gdijk** [comment]
pull requests created ;-)

**Comment by r4sky0** [comment]
Thank you! I will merge it into master next week!
