### ISSUE TITLE
USERAGENT UNKNOWN

### ISSUE THREAD

**Issue by PetrMa** [ralph-hm/check_paloalto#14]
Hello,
the command useragent reply the error "USERAGENT UNKNOWN".
Could you please let me know on which settings on Palo Alto depend this check? It is check of UserID-Agents in User Identification?

Thanks, Petr

**Comment by r4sky0** [comment]
Hello Petr,

unfortunately I don't have access to a PA-Firewall anymore, but I think your guess is right. The following key is queried through the REST-API:

```
<show><user><user-id-agent><state>all</state></user-id-agent></user></show>
```

I hope that helps. 

Kind regards
Ralph

**Comment by PetrMa** [comment]
Hello Ralph,
our company have installed SW version 8.1.3 which is the latest version of PA software. Maybe the REST-API query was changed for useragents in some last versions.
I have defined on each PA device the User-ID agent in menu Device - User Identification - UserID-Agents.

Could I help you to identify this issue? I can make any tests etc.

Regards,
Petr

**Comment by r4sky0** [comment]
Hello Petr,

sorry for the late reply.

Please try the following:

```
check_paloalto -H HOST -T TOKEN useragent -v -v -v
```

You should see something like this:

```
Reading XML from http://PA-IP/api/...cmd=
```

Please have a look at this URL and paste the XML output here.

**Comment by PetrMa** [comment]
Hello Ralph,
I tried the command you provided but with -v I already receive an error "check_paloalto: error: unrecognized arguments: -v" for all commands. The --verbose command receive the same error.

Petr

**Comment by r4sky0** [comment]
Sorry, please try the following command:

```
check_paloalto -H HOST -T TOKEN  -v -v -v useragent
````

**Comment by PetrMa** [comment]
Hello Ralph,
there is the result:

USERAGENT UNKNOWN
unknown: Unexpected query result!
Reading XML from: https://my_pa_server/api/?key=my_key&type=op&cmd=<show><user><user-id-agent><state>all</state></user-id-agent></user></show>

**Comment by r4sky0** [comment]
Hello Petr,

could you please open the URL and look for this key:

show -> user -> user-id-agent -> state -> all

I'm afraid the format may have been changed. The script expects the following format: https://github.com/ralph-hm/nagios_check_paloalto/blob/master/tests/xml/useragent_ok.xml

Kind regards
Ralph

**Comment by PetrMa** [comment]
Hello Ralph,
**the command get this data:**
./check_paloalto -H my_pa_server -T my_key -v -v -v useragent
USERAGENT UNKNOWN
unknown: Unexpected query result!
Reading XML from: https://my_pa_server/api/?key=my_key&type=op&cmd=<show><user><user-id-agent><state>all</state></user-id-agent></user></show>

**but the URL from web browser get correct data:**
https://my_pa_server/api/?key=my_key&type=op&cmd=<show><user><user-id-agent><state>all</state></user-id-agent></user></show>

**the result is:**
< response status="success">
< result>
< ![CDATA[ 
Agent: SKBTSNT44(vsys: vsys1) Host: 172.30.40.96(172.30.40.96):5007
	Status                                            : conn:idle
	Version                                           : 0x5
	num of connection tried                           : 14
	num of connection succeeded                       : 3
	num of connection failed                          : 11
	num of status msgs rcvd                           : 407356
	num of request of status msgs sent                : 407367
	num of request of ip mapping msgs sent            : 1886520
	num of request of new ip mapping msgs sent        : 0
	num of request of all ip mapping msgs sent        : 3
	num of user ip mapping msgs rcvd                  : 176038
	num of ip msgs rcvd but failed to proc            : 0
	num of user ip mapping add entries rcvd           : 93294
	num of user ip mapping del entries rcvd           : 2987
	num of request of group msgs sent                 : 0
	num of group msgs rcvd                            : 0
	num of group msgs recvd buf fail to proc          : 0
	num of xml data msgs rcvd                         : 0
	num of xml data msgs rcvd but failed to proc      : 0
	num of sync domain messages sent                  : 0
	num of sync domain messages received              : 0
	num of sync digest messages sent                  : 0
	num of sync digest messages received              : 0
	num of sync group messages sent                   : 0
	num of sync group messages received               : 0
	num of sync users messages sent                   : 0
	num of sync users messages received               : 0
	num of bloomfilter requests sent                  : 0
	num of bloomfilter response received              : 0
	num of bloomfilter response failed to proc        : 0
	num of bloomfilter resize requests sent           : 0
	Last heard(seconds ago)                           : 1
	Messages State:
	  Job ID                                          : 0
	  Sent messages                                   : 2293891
	  Rcvd messages                                   : 583397
	  Rcvd rate(msgs/s)                               : 0
	  Rcvd peak rate(msgs/s)                          : 1
	  Lost messages                                   : 1
	  Failed to send messages                         : 1
	  Failed to enqueue messages                      : 0
	  Queued sending msgs with priority 0             : 0
	  Queued sending msgs with priority 1             : 0
	  Queued rcvring msgs with priority 0             : 0
	  Queued rcvring msgs with priority 1             : 0
	Credential Enforcement Status : Disabled
  ]]> 
  < /result>
  < /response>


Please ignore my spaces after char "<". 

BR,
Petr

**Comment by r4sky0** [comment]
Hi Petr,

sorry for the late reply. They changed the API output for the user agents in the new version.

I implemented the following check before I start accessing the CDATA block:

https://github.com/ralph-hm/nagios_check_paloalto/blob/master/check_pa/modules/useragent.py#L47

You can try to remove that if-clause and insert the correct numbers in the following code lines. It would also be possible to parse the text, but I did without it, because it is a block without a fixed structure.

I will close the ticket as the new version isn't marked as compatible and I have no longer access to a PA firewall, so I'm not able to test the script against a newer version.

Kind regards
Ralph
