### ISSUE TITLE
throughput usage

### ISSUE THREAD

**Issue by ghost** [ralph-hm/check_paloalto#4]
throughput also requires -i / --interface [INTERFACE].  Something to comment in usage and help.

**Comment by r4sky0** [comment]
The next update will make the documentation and usage more clear.

The -i switch needs the name of the interface you want to measure. You can find it here: Network > Interfaces. e. g. ethernet1/1 

If you want to check more then one interface at once, you can separate them by comma. e. g. ethernet1/1, ethernet1/2, ethernet1/3

So to use the throughput command try the following:

```
check_paloalto -H {PA-IP} -T {TOKEN} throughput -i ethernet1/1
```
