### ISSUE TITLE
About the TOKEN

### ISSUE THREAD

**Issue by windsonshen** [ralph-hm/check_paloalto#5]
I don't how to ues the TOKEN.
I have Already gen the TOKEN at my PA like this
# <response status="success">
# <result>
# <key>

LUFRPT1sRUI4UEZZL2FNbStiMnhnVmdpU0RERGErZU09aGJpakxHU0Z1ZGE0SC9UbkhtQlNBcmJBcFpjM2pBbFNrUnJDNDlEbGlFVT0=
# </key>
# </result>
# </response>

how to use this???

**Comment by r4sky0** [comment]
You closed the issue, therefore i assume you found it out how to use the token?  

According to the documentation, all you have to do is installing the script and use (for example) the following command:

```
check_paloalto -H 192.168.0.1 -T LUFRPT1sRUI4UEZZL2FNbStiMnhnVmdpU0RERGErZU09aGJpakxHU0Z1ZGE0SC9UbkhtQlNBcmJBcFpjM2pBbFNrUnJDNDlEbGlFVT0= diskspace
```

To find out which commands you can use, you can refer either to the [documentation](https://nagios-check-paloalto.readthedocs.org/en/latest/usage.html) or you use the command:

```
check_paloalto -h
```

**Comment by windsonshen** [comment]
thank you very much.
yes, I have fine the TOKEN is the KEY which wan gen by PA.
but now ,when I want define command.cfg in NAGIOS.
I don't know how.

**Comment by ralph-hm** [comment]
To define a command, add the following to your commands.cfg:

```
define command {
       command_name    check_paloalto
       command_line    check_paloalto
       }
```

**Comment by windsonshen** [comment]
then how to define service, would PLZ give me a Example?

**Comment by r4sky0** [comment]
Try this instead:

command.cfg:

```
define command {
       command_name    check_paloalto
       command_line    check_paloalto -H $HOSTADDRESS$ -T LUFRPT1sRUI4UEZZL2FNbStiMnhnVmdpU0RERGErZU09aGJpakxHU0Z1ZGE0SC9UbkhtQlNBcmJBcFpjM2pBbFNrUnJDNDlEbGlFVT0= $ARG1$
       }
```

services.cfg

```
define service{
        use                     generic-service
        service_description     Available diskspace
        check_command           check_paloalto!diskspace 
        host_name               PaloAlto Host
        }
```

**Comment by windsonshen** [comment]
Error: Service check command 'check_paloalto!diskspace' specified in service 'Available diskspace' for host 'Car-plus-PA500' not defined anywhere!

**Comment by r4sky0** [comment]
Okay please try the following on your server CLI and paste the output:

```
check_paloalto -H (PA_IP) -T LUFRPT1sRUI4UEZZL2FNbStiMnhnVmdpU0RERGErZU09aGJpakxHU0Z1ZGE0SC9UbkhtQlNBcmJBcFpjM2pBbFNrUnJDNDlEbGlFVT0= diskspace
```

```
which check_paloalto
```

**Comment by windsonshen** [comment]
[nagios@Nagios etc]$ check_paloalto -H 58.210.77.247 -T LUFRPT1sRUI4UEZZL2FNbStiMnhnVmdpU0RERGErZU09aGJpakxHU0Z1ZGE0SC9UbkhtQlNBcmJBcFpjM2pBbFNrUnJDNDlEbGlFVT0= diskspace
DISKSPACE OK - sda2: 55% used space, sda5: 44% used space, sda6: 35% used space, sda8: 48% used space | sda2=55;85;95;0;100 sda5=44;85;95;0;100 sda6=35;85;95;0;100 sda8=48;85;95;0;100

**Comment by r4sky0** [comment]
Great and the second command?

`which check_paloalto`

**Comment by windsonshen** [comment]
[nagios@Nagios etc]$ which check_paloalto
/usr/bin/check_paloalto

**Comment by steadfasterX** [comment]
The error is about missing check command definition!

command.cfg

```
define command {
       command_name    check_paloalto
       command_line    /usr/bin/check_paloalto
       }
```

**Comment by windsonshen** [comment]
Stille the same 
I post my CFG file to you.
command.cfg

define command{
        command_name    check-paloalto  
        command_line    /usr/local/bin/check_paloalto -H $HOSTADDRESS$ -T LUFRPT1sRUI4UEZZL2FNbStiMnhnVmdpU0RERGErZU09aGJpakxHU0Z1ZGE0SC9UbkhtQlNBcmJBcFpjM2pBbFNrUnJDNDlEbGlFVT0= --option $ARG1$ \"$ARG2$" \"$ARG3$\"

nagios.cfg

cfg_file=/usr/local/nagios/etc/objects/checkpaloalto.cfg

checkpaloalto.cfg

define host{  
  use            linux-server  
  host_name        Car-plus-PA500  
  alias        Car-plus-PA500  
  address       58.210.77.247 
  } 
define hostgroup{  
  hostgroup_name      PaloAlto  
  alias        PaloAlto  
  members        Car-plus-PA500  
  }
###############################################################################
###############################################################################
#

# SERVICE DEFINITIONS

#
###############################################################################
###############################################################################

# Create a service for monitoring the uptime of the server

# Change the host_name to match the name of the host you defined above

define service{ 
use generic-service 
service_description Available diskspace 
check_command check_paloalto!diskspace 
host_name Car-plus-PA500 
  }

**Comment by windsonshen** [comment]
Error: Service check command 'check_paloalto!diskspace' specified in service 'Available diskspace' for host 'Car-plus-PA500' not defined anywhere!

**Comment by r4sky0** [comment]
**command.cfg**
Please replace your existing check_paloalto command definition with the following:

```
define command {
       command_name    check_paloalto
       command_line    /usr/bin/check_paloalto -H $HOSTADDRESS$ -T LUFRPT1sRUI4UEZZL2FNbStiMnhnVmdpU0RERGErZU09aGJpakxHU0Z1ZGE0SC9UbkhtQlNBcmJBcFpjM2pBbFNrUnJDNDlEbGlFVT0= $ARG1$
       }
```

If it doesn't work, please have a look at your nagios.cfg and check if you can find your command definition file.

`cfg_file = /path/to/nagios/command.cfg`

**Comment by steadfasterX** [comment]
Ok @windsonshen 

1) please define it **/usr/bin/check_paloalto** not /usr/**local**/bin/check_paloalto
(because the which command states **/usr/bin/**)
2) please correct your check command definition: 
**you defined** 
command_name check-paloalto (with a **MINUS**)
**it should be:**
command_name check**_**paloalto (with an **underscore**)

**Comment by windsonshen** [comment]
@xdajog Nothing happened

**Comment by steadfasterX** [comment]
same error?

**Comment by windsonshen** [comment]
yes

**Comment by windsonshen** [comment]
OK ,it's OK NOW.It's just the command definition
2) please correct your check command definition: 
you defined 
command_name check-paloalto (with a MINUS)
it should be:
command_name check_paloalto (with an underscore)

**Comment by steadfasterX** [comment]
yeah that one was tricky :+1: 
Glad to help you out !

and now have fun with this great plugin ;)

**Comment by windsonshen** [comment]
Car-plus-PA500
diskSpace
CRITICAL    04-10-2016 19:46:05 0d 0h 5m 44s    3/3 (No output on stdout) stderr: execvp(/usr/bin/check-paloalto, ...) failed. errno is 2: No such file or directory 
environmental
CRITICAL    04-10-2016 19:46:01 0d 0h 3m 48s    2/3 (No output on stdout) stderr: execvp(/usr/bin/check-paloalto, ...) failed. errno is 2: No such file or directory 
load
CRITICAL    04-10-2016 19:47:02 0d 0h 4m 47s    3/3 (No output on stdout) stderr: execvp(/usr/bin/check-paloalto, ...) failed. errno is 2: No such file or directory 
session info
CRITICAL    04-10-2016 19:47:11 0d 0h 2m 38s    2/3 (No output on stdout) stderr: execvp(/usr/bin/check-paloalto, ...) failed. errno is 2: No such file or directory 
throughput
CRITICAL    04-10-2016 19:46:36 0d 0h 5m 13s    3/3 (No output on stdout) stderr: execvp(/usr/bin/check-paloalto, ...) failed. errno is 2: No such file or directory

**Comment by windsonshen** [comment]
nagios no output?

**Comment by steadfasterX** [comment]
it is still a MINUS here!

**Comment by r4sky0** [comment]
CRITICAL 04-10-2016 19:46:01 0d 0h 3m 48s 2/3 (No output on stdout) stderr: execvp**(/usr/bin/check-paloalto, ...**) failed. errno is 2: No such file or directory 

Please change your command definition to check_paloalto! (underscore)

**Comment by steadfasterX** [comment]
I was faster @ralph-hm ;)

**Comment by windsonshen** [comment]
IT'S OK now.THANKs. Both of you!

**Comment by r4sky0** [comment]
You're welcome! :)
