### ISSUE TITLE
Measuring throughput on multiple identically configured PA's fails

### ISSUE THREAD

**Issue by gdijk** [ralph-hm/check_paloalto#8]
Hi,

We have a failover configuration, 2 PA3020's with interfaces with identical names.
I cannot get snmp reachable from the failover adres (perhaps it's possible?) so I check the throughput on both nodes.
However, the throughput checkfile has no mechanism that tells the plugin which values belong to what PA node, so the values are rather useless.
I solved it for now by creating and calling a second throughput.py that uses a different checkfile.
It would be nice however, if either the checkfile name could be passed on as an argument, or the hostname would be part of the checkfile.
Or is there a simpeler solution that I overlooked?

Kind regards

**Comment by r4sky0** [comment]
Hi gdijk,

thanks for the hint!

You are correct, i haven't thought of it yet. 

I will fix this in the next release. Probably i will add the IP or the hostname to identify the PA in the checkfile, so users don't have to pass an additional argument.

Kind regards
Ralph

**Comment by gdijk** [comment]
Thanks Ralph!

**Comment by r4sky0** [comment]
Hi gdijk,

the issue has been resolved.

Kind regards
Ralph

**Comment by gdijk** [comment]
And confirmed working now, thanks!
